# Wrangler configuration for Cloudflare Workers
# Replace the account_id and zone_id as needed. See Cloudflare dashboard.
name = "wb-proxy-worker"
main = "./worker.js"
compatibility_date = "2026-03-03"

# Uncomment and fill these values when you deploy with Wrangler CLI
# account_id = "<YOUR_ACCOUNT_ID>"
# workers_dev = true
# route = ""
# zone_id = ""
